config/routes.rb
Ppm::Application.routes.draw do
  root :to => 'posts#index'

  resources :questions do
    collection do
      get :mine
      get :unanswered
      get :answer
    end

    member do
      get :vote_up
      get :vote_down
    end
  end

  resources :posts do
    collection do
      get :top
      get :autocomplete_tag_name
      get :comment
      get :recent
    end

    member do
      get :unvote
      get :vote_up
      get :vote_down
    end
  end

  resources :answers do
    member do
      get :vote_up
      get :vote_down
    end
  end

  resources :comments

  devise_for :users, path_names: {sign_in: "login", sign_out: "signout"},
                     controllers: {omniauth_callbacks: "users/omniauth_callbacks", 
                        sessions: "users/sessions"}

  resources :users do
    collection do
      get :recent
      get :top
      get :search
    end
  end

  get 'tags/:tag', to: 'posts#index', as: :tag

end

app/views/shared/search_field/_search_field.html.erb
<%= form_tag posts_path, :method => 'get', :class => 'search' do %>
  <div class="input-prepend">
    <span class="add-on"><i class="icon-search"></i></span>
    <%= text_field_tag :query, params[:query], class: "input-xlarge", placeholder: t('.search') %>
  </div>
<% end %>

app/views/shared/search_field/_search_field_holder.html.erb
<div class="row-fluid">
  <div class="span8">
    <%= render 'shared/search_field/search_field' %>
  </div>
  <div class="span4">
    <%= link_to t('.ask'), new_question_path, :class => "btn btn-success pull-right" %>
  </div>
</div>